/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:f68272fd-6ec9-4764-ba7e-4a58d5ad6957",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_2o4ofAxBP",
    "aws_user_pools_web_client_id": "4i9i438d56bdra8h82v7anbh4o",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://f7p6xntpyjfxhmbuyigyac6tda.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
